exec-once = waybar &
exec-once = mako &
exec-once = swaybg -m fill -i ~/Pictures/wallpapers/tokyo-night.png &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = discord &
exec-once = spotify &
