general {
    grace = 5
    hide_cursor = true
}

background {
    path = ~/Pictures/wallpapers/tokyo-night.png
    blur_passes = 2
    blur_size = 4
}

input-field {
    size = 250, 50
    outline_thickness = 2
    fade_on_empty = false
    placeholder_text = Password...
    text-color = #c0caf5
    inner-color = #24283b
    outer-color = #7aa2f7
    check-color = #9ece6a
    error-color = #f7768e
}
